[package]
name = "gouge"
version = "0.1.0"
authors = ["Adam Richardson"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
web-sys = "^0.3"

[profile.dev]
lto = true
opt-level = 3
wasm-opt = false

[profile.release]
lto = true
opt-level = 3
wasm-opt = false